### ISSUE TITLE
IE Engineer's Workbench Missing Texture

### ISSUE THREAD

**Issue by rorotheworld** [shoveln/Consistency-Forge#1]
I'm playing [Valhelsia 3](https://www.curseforge.com/minecraft/modpacks/valhelsia-3) and using the Consistency-Forge pack causes the Engineer's Workbench from Immersive Engineering to have missing textures when placed as a block in-world. I'm assuming this has something to do with [Updated Engineering](https://www.curseforge.com/minecraft/texture-packs/updated-engineering), which is included with Valhelsia 3 by default.
 I played around with the load order but couldn't get it sorted out. I've unfortunately had to disable consistency-forge for the time being.

**Comment by shoveln** [comment]
It seems like at some point Immersive Engineering updated the formatting on multiblock models, and this broke placing the block in-world. The problem is independent of Updated Engineering, so you should be good to use both resource packs once Valhelsia updates to a newer version of Consistency-Forge.
